# Generated by Django 3.2.2 on 2021-12-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalDetails',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(default=0, null=True)),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('designationid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person')),
            ],
        ),
    ]
